name: Building And Testing
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm run --prefix 03_Module/27 install
      - name: Build production project
        run: npm run --prefix 03_Module/27 build:prod
        if: always()
      - name: Unit testing
        run: npm run --prefix 03_Module/27 test:unit
        if: always()
      - name: Build storybook
        run: npm run --prefix 03_Module/27 storybook:build
        if: always()
